# compiler setup
CC=gcc
CFLAGS=-Wall -Wextra -std=c99 -lm

# define targets
TARGETS=segment_display

build: $(TARGETS)

segment_display: Problema4.c
	$(CC) $(CFLAGS) Problema4.c -o segment_display

pack:
	zip -FSr 315CA_RotaruFlorisAdrian_Tema1.zip README Makefile *.c

clean:
	rm -f $(TARGETS)

.PHONY: pack clean
